apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-webapp.fullname" . }}
  labels:
    {{- include "frontend-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appConfig.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "frontend-webapp.selectorLabels" . | nindent 4 }}
